CREATE DATABASE CODING_;
USE CODING_;

CREATE TABLE CADASTRO (
	ID_USUARIO INT PRIMARY KEY auto_increment,
    NOME_USUARIO varchar(50) NOT NULL,
    EMAIL_USUARIO varchar(50) NOT NULL,
    DATA_NASC DATETIME NOT NULL,
    SENHA varchar(50) NOT NULL);

CREATE TABLE LOGIN (
	  EMAIL_USUARIO varchar(50) PRIMARY KEY,
      SENHA varchar(50) NOT NULL);

CREATE TABLE MODULO (
	ID_MODULO INT PRIMARY KEY auto_increment,
    LINGUAGEM varchar(50) NOT NULL,
    NOME_MODULO varchar(50) NOT NULL);
    
CREATE TABLE CONTEUDO ( 
	ID_CONTEUDO INT PRIMARY KEY auto_increment,
    CONTEUDO LONGTEXT,
    FK_CONTEUDO_MOD INT NOT NULL,
	CONSTRAINT FK_CONTEUDO FOREIGN KEY (FK_CONTEUDO_MOD) REFERENCES MODULO (ID_MODULO));
    
    
CREATE TABLE QUESTAO (
	ID_QUESTAO INT PRIMARY KEY auto_increment,
    NOME_MODULO varchar(50) NOT NULL,
    FK_ID_MODULO INT,
    CONSTRAINT FK_ID_MOD FOREIGN KEY (FK_ID_MODULO) REFERENCES MODULO (ID_MODULO));
    
CREATE TABLE BOLETIM (
	ID_BOLETIM INT PRIMARY KEY auto_increment,
    FK_ID_USUARIO INT NOT NULL,
    FK_ID_MODULO INT NOT NULL,
	CONSTRAINT FK_USUARIO FOREIGN KEY (FK_ID_USUARIO) REFERENCES CADASTRO (ID_USUARIO),
    CONSTRAINT FK_MODULO FOREIGN KEY (FK_ID_MODULO) REFERENCES MODULO (ID_MODULO));
    
    
         INSERT INTO CADASTRO ( NOME_USUARIO, EMAIL_USUARIO, DATA_NASC, SENHA) 
                     values ('Jose da Silva','silva@provedor.com', '1980/02/02','123456');
	SELECT * FROM CADASTRO;
    
          
       INSERT INTO LOGIN ( EMAIL_USUARIO, SENHA) 
                     values ('silva@LINDA.com','1I3456');
                     SELECT * FROM LOGIN;
                     
		
		   INSERT INTO MODULO ( LINGUAGEM, NOME_MODULO) 
                     values ('PHP','INICIO');
                     SELECT * FROM MODULO;